"""Week 2: Add EventLog, Items, update UserStats/Skill/JournalEntry

Revision ID: 4256528dec5e
Revises: 9742281773f4
Create Date: 2026-02-08 08:32:13.659654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4256528dec5e'
down_revision: Union[str, Sequence[str], None] = '9742281773f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('effect', sqlite.JSON(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('is_consumable', sa.Boolean(), nullable=False),
    sa.Column('effect_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('item_metadata', sqlite.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_templates_category'), 'item_templates', ['category'], unique=False)
    op.create_index(op.f('ix_item_templates_item_type'), 'item_templates', ['item_type'], unique=False)
    op.create_index(op.f('ix_item_templates_name'), 'item_templates', ['name'], unique=True)
    op.create_table('event_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_payload', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_logs_created_at', 'event_logs', ['created_at'], unique=False)
    op.create_index('ix_event_logs_event_type', 'event_logs', ['event_type'], unique=False)
    op.create_index('ix_event_logs_user_event', 'event_logs', ['user_id', 'event_type'], unique=False)
    op.create_index('ix_event_logs_user_id', 'event_logs', ['user_id'], unique=False)
    op.create_table('user_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.Column('is_consumed', sa.Boolean(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('item_metadata', sqlite.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['item_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_items_template_id'), 'user_items', ['template_id'], unique=False)
    op.create_index('ix_user_items_user_equipped', 'user_items', ['user_id', 'is_equipped'], unique=False)
    op.create_index(op.f('ix_user_items_user_id'), 'user_items', ['user_id'], unique=False)
    op.add_column('journal_entries', sa.Column('processing_status', sa.String(length=20), nullable=False))
    op.add_column('journal_entries', sa.Column('processing_error', sa.String(length=500), nullable=True))
    op.add_column('journal_entries', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('journal_entries', sa.Column('last_retry_at', sa.DateTime(), nullable=True))
    op.add_column('skills', sa.Column('limit_break_progress', sa.Integer(), nullable=False))
    op.add_column('skills', sa.Column('limit_break_unlocked', sa.Boolean(), nullable=False))
    op.add_column('skills', sa.Column('limit_break_condition', sa.JSON(), nullable=True))
    op.add_column('user_stats', sa.Column('karma', sa.Integer(), nullable=False))
    op.add_column('user_stats', sa.Column('karma_breakdown', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_stats', 'karma_breakdown')
    op.drop_column('user_stats', 'karma')
    op.drop_column('skills', 'limit_break_condition')
    op.drop_column('skills', 'limit_break_unlocked')
    op.drop_column('skills', 'limit_break_progress')
    op.drop_column('journal_entries', 'last_retry_at')
    op.drop_column('journal_entries', 'retry_count')
    op.drop_column('journal_entries', 'processing_error')
    op.drop_column('journal_entries', 'processing_status')
    op.drop_index(op.f('ix_user_items_user_id'), table_name='user_items')
    op.drop_index('ix_user_items_user_equipped', table_name='user_items')
    op.drop_index(op.f('ix_user_items_template_id'), table_name='user_items')
    op.drop_table('user_items')
    op.drop_index('ix_event_logs_user_id', table_name='event_logs')
    op.drop_index('ix_event_logs_user_event', table_name='event_logs')
    op.drop_index('ix_event_logs_event_type', table_name='event_logs')
    op.drop_index('ix_event_logs_created_at', table_name='event_logs')
    op.drop_table('event_logs')
    op.drop_index(op.f('ix_item_templates_name'), table_name='item_templates')
    op.drop_index(op.f('ix_item_templates_item_type'), table_name='item_templates')
    op.drop_index(op.f('ix_item_templates_category'), table_name='item_templates')
    op.drop_table('item_templates')
    # ### end Alembic commands ###
