"""add autostart conditions to quests

Revision ID: 4ce8e78ab15d
Revises: af8ae06585ff
Create Date: 2026-02-10 00:04:13.331419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce8e78ab15d'
down_revision: Union[str, Sequence[str], None] = 'af8ae06585ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mq_templates', sa.Column('autostart_condition', sa.JSON(), nullable=True))
    op.add_column('user_mq', sa.Column('autostart_condition', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_mq', 'autostart_condition')
    op.drop_column('mq_templates', 'autostart_condition')
    # ### end Alembic commands ###
