"""Initial models

Revision ID: 9742281773f4
Revises: 
Create Date: 2026-02-05 15:50:07.415871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9742281773f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mq_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description_template', sa.String(length=1000), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('structure', sa.String(length=50), nullable=True),
    sa.Column('completion_condition', sa.JSON(), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.Column('reward_coins', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mq_templates_category'), 'mq_templates', ['category'], unique=False)
    op.create_index(op.f('ix_mq_templates_name'), 'mq_templates', ['name'], unique=False)
    op.create_table('title_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description_template', sa.String(length=500), nullable=True),
    sa.Column('effect', sa.JSON(), nullable=False),
    sa.Column('rank', sa.String(length=1), nullable=False),
    sa.Column('unlock_condition', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_title_templates_category'), 'title_templates', ['category'], unique=False)
    op.create_index(op.f('ix_title_templates_name'), 'title_templates', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('journal_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ai_categories', sa.JSON(), nullable=False),
    sa.Column('ai_suggested_quests', sa.JSON(), nullable=False),
    sa.Column('ai_processed', sa.Boolean(), nullable=False),
    sa.Column('manual_theme_ids', sa.JSON(), nullable=False),
    sa.Column('manual_skill_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_table('themes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Float(), nullable=False),
    sa.Column('xp_to_next_level', sa.Float(), nullable=False),
    sa.Column('corrosion_level', sa.String(length=20), nullable=False),
    sa.Column('parent_theme_id', sa.String(length=36), nullable=True),
    sa.Column('theme_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['parent_theme_id'], ['themes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themes_parent_theme_id'), 'themes', ['parent_theme_id'], unique=False)
    op.create_index(op.f('ix_themes_user_id'), 'themes', ['user_id'], unique=False)
    op.create_table('user_mq',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('parent_mq_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('personalized_description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completion_progress', sa.Integer(), nullable=False),
    sa.Column('completion_target', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_mq_id'], ['user_mq.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['mq_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_mq_parent_mq_id'), 'user_mq', ['parent_mq_id'], unique=False)
    op.create_index(op.f('ix_user_mq_template_id'), 'user_mq', ['template_id'], unique=False)
    op.create_index(op.f('ix_user_mq_user_id'), 'user_mq', ['user_id'], unique=False)
    op.create_table('user_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('mp', sa.Integer(), nullable=False),
    sa.Column('mental_health', sa.Integer(), nullable=False),
    sa.Column('physical_health', sa.Integer(), nullable=False),
    sa.Column('relationship_quality', sa.Integer(), nullable=False),
    sa.Column('socialization_level', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_stats_user_id'), 'user_stats', ['user_id'], unique=True)
    op.create_table('user_titles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title_template_id', sa.String(length=36), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False),
    sa.Column('personalized_description', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['title_template_id'], ['title_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_titles_title_template_id'), 'user_titles', ['title_template_id'], unique=False)
    op.create_index(op.f('ix_user_titles_user_id'), 'user_titles', ['user_id'], unique=False)
    op.create_table('skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('theme_id', sa.String(length=36), nullable=True),
    sa.Column('parent_skill_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Float(), nullable=False),
    sa.Column('xp_to_next_level', sa.Float(), nullable=False),
    sa.Column('rank', sa.String(length=20), nullable=False),
    sa.Column('practice_time_minutes', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('skill_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['parent_skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_parent_skill_id'), 'skills', ['parent_skill_id'], unique=False)
    op.create_index(op.f('ix_skills_theme_id'), 'skills', ['theme_id'], unique=False)
    op.create_index(op.f('ix_skills_user_id'), 'skills', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_user_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_theme_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_parent_skill_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_user_titles_user_id'), table_name='user_titles')
    op.drop_index(op.f('ix_user_titles_title_template_id'), table_name='user_titles')
    op.drop_table('user_titles')
    op.drop_index(op.f('ix_user_stats_user_id'), table_name='user_stats')
    op.drop_table('user_stats')
    op.drop_index(op.f('ix_user_mq_user_id'), table_name='user_mq')
    op.drop_index(op.f('ix_user_mq_template_id'), table_name='user_mq')
    op.drop_index(op.f('ix_user_mq_parent_mq_id'), table_name='user_mq')
    op.drop_table('user_mq')
    op.drop_index(op.f('ix_themes_user_id'), table_name='themes')
    op.drop_index(op.f('ix_themes_parent_theme_id'), table_name='themes')
    op.drop_table('themes')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_title_templates_name'), table_name='title_templates')
    op.drop_index(op.f('ix_title_templates_category'), table_name='title_templates')
    op.drop_table('title_templates')
    op.drop_index(op.f('ix_mq_templates_name'), table_name='mq_templates')
    op.drop_index(op.f('ix_mq_templates_category'), table_name='mq_templates')
    op.drop_table('mq_templates')
    # ### end Alembic commands ###
