"""add autostart flags to quests

Revision ID: af8ae06585ff
Revises: 4256528dec5e
Create Date: 2026-02-10 00:01:04.486243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af8ae06585ff'
down_revision: Union[str, Sequence[str], None] = '4256528dec5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'mq_templates',
        sa.Column('autostart', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    )
    op.add_column(
        'user_mq',
        sa.Column('autostart', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    )
    op.add_column(
        'user_mq',
        sa.Column('metadata', sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_mq', 'metadata')
    op.drop_column('user_mq', 'autostart')
    op.drop_column('mq_templates', 'autostart')
    # ### end Alembic commands ###
